"""rename notificata to gestita in assenze

Revision ID: 1585e75917cc
Revises: bbd37d4b261b
Create Date: 2024-12-12 17:52:34.290089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1585e75917cc'
down_revision = 'bbd37d4b261b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assenza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gestita', sa.Boolean(), nullable=True))
        batch_op.drop_column('notificata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assenza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificata', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('gestita')

    # ### end Alembic commands ###
