"""modifica db

Revision ID: 6146f32a956e
Revises: ef5b9e4ab8bf
Create Date: 2024-06-15 01:24:32.231021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6146f32a956e'
down_revision = 'ef5b9e4ab8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('utenza_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['utenza_id'], ['utenza.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turno')
    # ### end Alembic commands ###
