"""add password salt

Revision ID: a4fd6c867423
Revises: 6146f32a956e
Create Date: 2024-12-12 15:38:30.734284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fd6c867423'
down_revision = '6146f32a956e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenza', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
