"""add assenze table

Revision ID: bbd37d4b261b
Revises: 5841d3028dc0
Create Date: 2024-12-12 17:43:12.080967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd37d4b261b'
down_revision = '5841d3028dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assenza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('data_comunicazione', sa.DateTime(), nullable=True),
    sa.Column('notificata', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assenza')
    # ### end Alembic commands ###
